### ISSUE TITLE
The underlying connection was closed: A connection that was expected to be kept alive was closed by the server

### ISSUE THREAD

**Issue by contourkde** [AsBuiltReport/AsBuiltReport.VMware.vSphere#104]
**Describe the bug**

When the script is running, suddenly after some time a message that say appear:

New-AsBuiltReport : The underlying connection was closed: A connection that was expected to be kept alive 
was closed by the server.
 

**To Reproduce**
1. Go to the folder where the script is
2. Click on 'open an powershell in admin mode (where trying with PS ISE, PS v5 and PS v7 as well'
3. Run command New-AsBuiltReport -Report VMware.vSphere -Target 'vCenterFQDN' -EnableHealthCheck  -Verbose 
4. 
![image](https://user-images.githubusercontent.com/35497727/194668827-c0c294d8-9d5f-4023-b99c-98cb629cf412.png)

**Expected behavior**
That the DOc document were generated.

**Screenshots**

**System (please provide the following information about the system from which you are trying to generate a report):**
 - OS: Windows 10
 - Windows PowerShell version 
 - 
![image](https://user-images.githubusercontent.com/35497727/194669014-df2dcfb2-2e69-4e45-bfab-fba8b5b3376d.png)
![image](https://user-images.githubusercontent.com/35497727/194669040-b1ddf2c4-7e57-45bb-911c-c462aaad1603.png)
![image](https://user-images.githubusercontent.com/35497727/194669072-2eb32c68-7ea4-4e90-aa3b-d46385df5f42.png)

 - 3rd party PowerShell module name and version [e.g. VMware PowerCLI 11.2]
![image](https://user-images.githubusercontent.com/35497727/194669205-51869def-9c2c-40b5-a966-38fbf1a4db84.png)

 - AsBuiltReport Core module version [e.g. 1.0.0]

 - AsBuiltReport Report module name and version [e.g. AsBuiltReport.VMware.vSphere 1.0.0]

![image](https://user-images.githubusercontent.com/35497727/194669311-02d4761c-60fd-43c8-8d78-fa618f57a9fa.png)

**Additional context**
vCenter versioon 6.5
user with admin privileges on domain (user@company-domain.com)
I have to run this amazing tool with several vCenters and only in 1 on those had those problems. it has 4300 vms and 250 hosts

**Comment by tpcarman** [comment]
What is the output of `Get-PowerCLIConfiguration`? 

Perhaps try and increase the `WebOperationTimeoutSeconds` parameter?

`Set-PowerCLIConfiguration -WebOperationTimeoutSeconds 600`

**Comment by tpcarman** [comment]
Closing this issue due to lack of response. Please reopen if you continue to experience issues.
