### ISSUE TITLE
Asbuilt for vSphere errors stops running

### ISSUE THREAD

**Issue by JeremyHaynes-devguy** [AsBuiltReport/AsBuiltReport.VMware.vSphere#110]
**Describe the bug**
This is the error (I removed the servername)
New-AsBuiltReport : The variable '$Images' cannot be retrieved because it has not been set.
At line:1 char:1
+ New-AsBuiltReport -Report VMware.vSphere -Target 'XXXXXXX ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport
**To Reproduce**

Running New-AsBuiltReport against Vsphere

**Expected behavior**
I expected the report to be generated

**Screenshots**

**System (please provide the following information about the system from which you are trying to generate a report):**
 - OS: Windows 2019
 - Windows PowerShell version [Provide output from the following command: `$PSVersionTable.PSVersion`]
 - Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  3770

 - 3rd party PowerShell module name and version [e.g. VMware PowerCLI 11.2]
VMware.PowerCLI 13.1.0 build 21624340

 - AsBuiltReport Core module version [e.g. 1.0.0]
 
1.3.0      AsBuiltReport.Core

 - AsBuiltReport Report module name and version [e.g. AsBuiltReport.VMware.vSphere 1.0.0]
 
1.3.3.1    AsBuiltReport.VMware.vSphere

**Additional context**

**Comment by rebelinux** [comment]
Could you do a test by disabling the generation of the cover page image?

Step 1: Generate a ReportConfig

New-AsBuiltReportConfig -Report VMware.vSphere -FolderPath <User specified folder> -Filename <Optional>

Step 2: Set ShowCoverPageImage to false

![image](https://user-images.githubusercontent.com/1002783/234879704-660f6882-e11e-4174-8af2-d4e3122540ef.png)

Step 3: Run the report using the new configuration file.

New-AsBuiltReport -Report VMware.vSphere -Target vcenter.pharmax.local -Username 'administrator@vsphere.local' -Password 'P@ssw0rd' -Format Html,Word -OutputFolderPath 'C:\Users\Jon\Documents' **-ReportConfigFilePath 'C:\Users\Jon\AsBuiltReport\AsBuiltReport.VMware.vSphere.json'** -Verbose

Documentation: 

https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere#pencil2-configuration

**Comment by tpcarman** [comment]
I will close this issue as there has been no further response. You may reopen this issue if required.
