### ISSUE TITLE
Cannot Bind Argument to Parameter "Rows" because its is empty collection following PCI devices.

### ISSUE THREAD

**Issue by childebrandt42** [AsBuiltReport/AsBuiltReport.VMware.vSphere#115]
**Describe the bug**
Cannot Bind Argument to Parameter "Rows" because its is empty collection following PCI devices.

**To Reproduce**
1. Run AsBuilt agains lab, makes it to PCI devices and crashes with the error: Cannot Bind Argument to Parameter "Rows" because its is empty collection following PCI devices.
2. This is happening due to there being no PCI devices in my lab hosts. 

**Expected behavior**
Expect error handling to skip past issue when no PCI devices exist

**Screenshots**
![image](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/assets/13688057/400bf847-f3b1-4610-86bb-e3d3efd12dae)

**System (please provide the following information about the system from which you are trying to generate a report):**
 - OS: Windows 11
 - Windows PowerShell version 5.1 Build 22621

**Additional context**

**Comment by tpcarman** [comment]
Duplicate issue #111
