### ISSUE TITLE
vSphere 8.0.2-22617221 - New-AsBuiltReport : Cannot bind argument to parameter 'Rows' because it is an empty collection.

### ISSUE THREAD

**Issue by villan0s** [AsBuiltReport/AsBuiltReport.VMware.vSphere#116]
### Bug description

VERBOSE: [ 14:18:43:080 ] [ Document ] - Processing table 'PCI Devices Drivers & Firmware - xxxxx.xxxxx.xx'.
New-AsBuiltReport: Cannot bind argument to parameter 'Rows' because it is an empty collection.

### Command-line input

New-AsBuiltReport -Report VMware.vSphere -Target xxxxxx -Username administrator@vsphere.local -Password xxxxxxx -Format Html,Word -OutputFolderPath C:\Users\xxxxxx\Documents -Timestamp -Verbose

### Steps to reproduce

1.- Install-Module -Name VMware.PowerCLI
2.- Install-Module -Name AsBuiltReport.VMware.vSphere
3.- Run AsBuiltReport 
4.- Update file "Src/Public/Invoke-AsBuiltReport.VMware.vSphere.ps1" (https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/blob/dev/Src/Public/Invoke-AsBuiltReport.VMware.vSphere.ps1)
5.- Reboot
6.- Run AsBuiltReport

### Expected behaviour

Creating the vCenter report with the AsBuiltReport tool

### Screenshots

![Error](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/assets/151955342/31e41f47-4dfd-4345-89f9-a9a119ea3d10)

### Operating System

Windows 10 Enterprise Version 22H2
vCenter: 8.0.2-22617221
VMware ESXi: 8.0.2, 22380479 Dell Custom Image

### PowerShell Version

PSVersion 7.4.0
PSEdition Core
GitCommitId 7.4.0
OS Microsoft Windows 10.0.19045
Platform Win32NT
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
WSManStackVersion 3.0

### PowerShell Modules

AsBuiltReport.Core 1.3.0
AsBuiltReport.VMware.vSphere 1.3.3.1
PScribo 0.10.0

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/issues) before submitting this bug report.

**Comment by villan0s** [comment]
I have tested the functionality again by running it from the same computer, against a server with vCenter 7 and it generates the report without problems.

**Comment by aderusha** [comment]
I'm seeing the same behavior here, vCenter 8, client is Win 11 with PowerShell 7.4.0 and PowerCLI 13.2.0, fails trying to list out PCI devices on the first host it hits.

**Comment by mpacholke** [comment]
How can I obtain the RC ?

+ Install-Module -Name AsBuiltReport.VMware.vSphere -AllowPrerelease
+                                                   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module


I tried to install 1.3.3.1 and copied the files manually but I got the message the the report type is  unknown.
Must RC reside in a directory AsBuiltReport.VMware.vSphere-dev ?

**Comment by villan0s** [comment]
I just installed version 1.3.4-rc1 and ran the report again, and it finished without problems, now I will review the report if there are no problems.

**Comment by mpacholke** [comment]
Did you test any other OS than Windows?
I tried Windows Server 2016 with PS5.1 and got an error that  -AllowPrerelease is not valid.
On MACOS Sonoma and PWSH7 I got another error: 

install-Module -Name AsBuiltReport.VMware.vSphere -AllowPrerelease
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
Install-Package: No match was found for the specified search criteria and module name 'AsBuiltReport.VMware.vSphere'. Try Get-PSRepository to see all available registered module repositories.

Get-PackageSource PSGallery

Name                             ProviderName     IsTrusted  Location
----                             ------------     ---------  --------
PSGallery                        PowerShellGet    False      https://www.powershellgallery.com/api/v2

**Comment by rebelinux** [comment]
> Did you test any other OS than Windows? I tried Windows Server 2016 with PS5.1 and got an error that -AllowPrerelease is not valid. On MACOS Sonoma and PWSH7 I got another error:
> 
> install-Module -Name AsBuiltReport.VMware.vSphere -AllowPrerelease WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'. Install-Package: No match was found for the specified search criteria and module name 'AsBuiltReport.VMware.vSphere'. Try Get-PSRepository to see all available registered module repositories.
> 
> Get-PackageSource PSGallery
> 
> Name ProviderName IsTrusted Location
> 
> PSGallery PowerShellGet False https://www.powershellgallery.com/api/v2

Can you try this?

https://woshub.com/unable-resolve-package-source-powershell/

**Comment by mpacholke** [comment]
I run the latest MACOS-Update and set the TLS but the command only installs this modules:

 install-Module -Name AsBuiltReport.VMware.vSphere -AllowPrerelease
 Get-Module -ListAvailable @("AsBuiltReport.Core" ;"AsBuiltReport.Wware. vSphere"; "PSPKI";"PScriboChar
>> ts";"PScribo") | Select Name, Version

Name               Version
----               -------
AsBuiltReport.Core 1.3.0
PScribo            0.10.0

**Comment by rebelinux** [comment]
On Windows 2016 you need to update the 'PowerShellGet' version to latest release

`Update-Module PowerShellGet -Force`

**Comment by rebelinux** [comment]
On Windows 2016 you need to update the 'PowerShellGet' version to latest release

```
PS C:\Users\Administrator> install-Module -Name AsBuiltReport.VMware.vSphere -AllowPrerelease
Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
At line:1 char:51
+ install-Module -Name AsBuiltReport.VMware.vSphere -AllowPrerelease
+                                                   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module

PS C:\Users\Administrator>
```
Install or update PowerShellGet

```
Install-Module PowerShellGet -Force
Update-Module PowerShellGet -Force
```

Then close and reopen a new powershell console.

```
PS C:\Users\Administrator> install-Module -Name AsBuiltReport.VMware.vSphere -AllowPrerelease

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
```

```
PS C:\Users\Administrator> Get-Module -ListAvailable AsBuiltReport.VMware.vSphere


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.3.4      AsBuiltReport.VMware.vSphere        Invoke-AsBuiltReport.VMware.vSphere


PS C:\Users\Administrator>
```
