### ISSUE TITLE
Host Network Section - NSX-T virtual switch portgroup labels are erroneously associated with a VMKernel port

### ISSUE THREAD

**Issue by atkinsroy** [AsBuiltReport/AsBuiltReport.VMware.vSphere#118]
### Bug description

In the VMKernel adapters section of the document, some VMkernel ports have all labels associated with them, when there should be none. I've isolated the issue to the following code:

``
'Network Label' = & {
   if ($_.Spec.Portgroup) {
       $script:pg = $_.Spec.Portgroup
   } 
   else {
        $script:pg = Get-View -ViewType DistributedVirtualPortgroup -Property Name, Key -Filter @{'Key' = "$($_.Spec.DistributedVirtualPort.PortgroupKey)" } | Select-Object -ExpandProperty Name
   }
   $script:pg
}
``

The -filter accepts a value. In my case there is no PortgroupKey, and there is therefore no filter so all portgroup labels are displayed. This is an NSX-T managed switch, so this might be the reason that perhaps you've not seen this before.

### Command-line input

New-AsbuiltReport -Report VMware.vSphere

### Steps to reproduce

$View = Get-VMhost -Server X | Get-View
$NetSys = Get-View $View.ConfigManager.NetworkSystem
$Vnic = $NetSys.NetworkInfo.Vnic
($Vnic | ? Device -eq 'vmk0').Spec.DistributedVirtualPort.PortgroupKey  # This has a value, so -Filter above works.

($Vnic | ? Device -eq 'vmk10').Spec.DistributedVirtualPort.PortgroupKey  # This has no value, so -Filter above displays all portgroup labels.

### Expected behaviour

In the vSphere client, these kernel ports show a dash under network label. So I guess that's the expected behaviour here too.

### Screenshots

![image](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/assets/6621844/49585aa8-84c1-4b6e-a693-9d1681a55640)

![image](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/assets/6621844/d71974ca-fa86-4a14-bf42-be11ba85b2d9)

### Operating System

Windows

### PowerShell Version

![image](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/assets/6621844/86e14df5-c6d2-4a43-ac92-cedc135f4a96)

### PowerShell Modules

![image](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/assets/6621844/dd639c3c-0e3a-4055-8d36-2d84c9686797)

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/issues) before submitting this bug report.

**Comment by atkinsroy** [comment]
Here's how I've tackled it. This appears to work in an NSX-T environment:

```
foreach ($Vmk in $VmKernel) {
            if ($Vmk.Spec.PortGroup) {
                $NetLabel += $Vmk.Spec.PortGroup
            }
            else {
                if ($Vmk.Spec.DistributedVirtualPort.Portgroupkey) {
                    $NetLabel += ($DvPortGroup | Where-Object Key -eq $Vmk.Spec.DistributedVirtualPort.Portgroupkey).Name
                }
                else {
                    $NetLabel += '--'
                }
            }
.
.
.
```

**Comment by tpcarman** [comment]
I see the issue.

![image](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/assets/15333667/e7cecee3-449a-469b-bedf-58c3e39f45d1)

![image](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/assets/15333667/d000a7a6-2083-41bb-a0e1-6453c1966e64)
