### ISSUE TITLE
Host physical adapters section only shows vSwitch info, not distributed switch

### ISSUE THREAD

**Issue by mattallford** [AsBuiltReport/AsBuiltReport.VMware.vSphere#27]
**Describe the bug**
In the section for host physical adapters, the report currently only shows the name of a virtual standard switch (vSwitch) that a vmnic is associated with. If the vmnic is associated with a distributed switch, it is not shown here.

**To Reproduce**
1. Run the report in an environment where hosts are connected to a distributed switch
2. Review the "Physical Adapters" section of the report and observe the 'vSwitch' column is empty

**Expected behavior**
This table should list the name of the switch the vmnic is associated with whether is be a standard or distributed switch.

**Screenshots**
![image](https://user-images.githubusercontent.com/16998139/55667400-85dac300-58a7-11e9-9476-5e94fd24749c.png)

**System (please provide the following information about the system from which you are trying to generate a report):**
 - OS: Windows 10
 - Windows PowerShell version: 5.1
 - 3rd party PowerShell module name and version: VMware PowerCLI 11.2
 - AsBuiltReport Core module version: 1.0.0
 - AsBuiltReport Report module name and version: AsBuiltReport.VMware.vSphere 1.0.0

**Comment by tpcarman** [comment]
Fix to be included in next release

```powershell
'vSwitch' = 
    if ($VMHost.ExtensionData.Config.Network.Vswitch.Pnic -contains $PhysicalNetAdapter.Key) {
        ($VMHost.ExtensionData.Config.Network.Vswitch | Where-Object {$_.Pnic -eq $PhysicalNetAdapter.Key}).Name
    } elseif ($VMHost.ExtensionData.Config.Network.ProxySwitch.Pnic -contains $PhysicalNetAdapter.Key) {
        ($VMHost.ExtensionData.Config.Network.ProxySwitch | Where-Object {$_.Pnic -eq $PhysicalNetAdapter.Key}).DvsName
    } else {
        '--'
    }
```
