### ISSUE TITLE
Additional iSCSI software storage adapter settings

### ISSUE THREAD

**Issue by mwrobo20** [AsBuiltReport/AsBuiltReport.VMware.vSphere#32]
**Is your feature request related to a problem? Please describe.**
I have a client requesting the report include specific settings related to the iSCSI software storage adapter.  Additional settings I would like to add to the report on the iSCSI software storage adapter..

Authentication Method
Authentication Method Account Name
Advanced Options
Network Port Binding - (Port Group, vmk adapter, Port Group Policy, Path Status, Physical Network Adapter)
Targets - Dynamic Discovery (iSCSI server list)

**Describe the solution you'd like**
I would like to know how to amend the script to include the above.

**Describe alternatives you've considered**
No alternatives considered. Reviewed Invoke-AsBuiltReport.VMware.vSphere.ps1 but not sure how to alter code to get what I need.

**Additional context**
No other context.

Thanks for your assistance.

**Comment by mattallford** [comment]
Hi @mwrobo20,

Thanks for the suggestion.

Would you like to learn how to contribute to the project? @tpcarman and I would be happy to teach you.

If yes, then your first task is figuring out how to pull out the information you described using PowerCLI. Once you have that, we can work with you on how you can contribute :)

If no, then we'll add it to the backlog and hopefully one of us or another contributor can add it in soon!

Cheers, Matt.

**Comment by mwrobo20** [comment]
Hi Matt!

Thanks for the quick response. I am working on pulling the data. Hope to have it by middle of next week.

Thanks,

Mike

**Comment by tpcarman** [comment]
Note: Advanced Options will be shown when VMHost InfoLevel is set to 5

![image](https://user-images.githubusercontent.com/15333667/62833585-a915e480-bc84-11e9-8320-3f3d6d863b33.png)
