### ISSUE TITLE
AsbuiltReport fails when scanning the HCX Cloud Gateway (CGW) dummy host

### ISSUE THREAD

**Issue by akvirtualgeek** [AsBuiltReport/AsBuiltReport.VMware.vSphere#36]
**Describe the bug**
The AsBuiltReport script fails to scan the hardware as well as trying to get to the ESXCLI of the HCX Dummy Host.

**To Reproduce**
1. Deploy HCX with the CGW
2. You'll see a host appear in vCenter that has cpu, ram and storage but no VMs.
3. Run Script

**Expected behavior**
Perhaps the script could recognize the HCX host and skip any further operations. 

**Screenshots**
VERBOSE: [ 11:00:48:742 ] [ Document ] - Processing blank line.
Get-EsxCli : 5/7/2019 11:00:50 AM       Get-EsxCli              Object of type 'InternalVimApi_50.ManagedObjectReference' cannot be converted to type 'System.String'.
At C:\Program Files\WindowsPowerShell\Modules\AsBuiltReport.VMware.vSphere\1.0.0\Src\Public\Invoke-AsBuiltReport.VMware.vSphere.ps1:1602 char:55
+ ...             $esxcli = Get-EsxCli -VMHost $VMHost -V2 -Server $vCenter
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-EsxCli], VimException
    + FullyQualifiedErrorId : Core_BaseCmdlet_UnknownError,VMware.VimAutomation.ViCore.Cmdlets.Commands.EsxCli.GetEsxCli

Get-VMHostHardware : 5/7/2019 11:00:51 AM       Get-VMHostHardware              The operation is not supported on the object.
At C:\Program Files\WindowsPowerShell\Modules\AsBuiltReport.VMware.vSphere\1.0.0\Src\Public\Invoke-AsBuiltReport.VMware.vSphere.ps1:1603 char:63
+ ...                  $VMHostHardware = Get-VMHostHardware -VMHost $VMHost
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-VMHostHardware], VimException
    + FullyQualifiedErrorId : Core_BaseCmdlet_UnknownError,VMware.VimAutomation.ViCore.Cmdlets.Commands.Host.GetVMHostHardware

VERBOSE: [ 11:00:51:474 ] [ Document ] - Processing table '10.109.8.41 ESXi Host Detailed Information'.
VERBOSE: [ 11:00:51:548 ] [ Document ] - Processing section 'Boot Device' started.
Get-EsxCli : 5/7/2019 11:00:51 AM       Get-EsxCli              Object of type 'InternalVimApi_50.ManagedObjectReference' cannot be converted to type 'System.String'.
At C:\Program Files\WindowsPowerShell\Modules\AsBuiltReport.VMware.vSphere\1.0.0\Src\Public\Invoke-AsBuiltReport.VMware.vSphere.ps1:285 char:19
+         $esxcli = Get-EsxCli -V2 -VMHost $vmhost -Server $vCenter
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-EsxCli], VimException
    + FullyQualifiedErrorId : Core_BaseCmdlet_UnknownError,VMware.VimAutomation.ViCore.Cmdlets.Commands.EsxCli.GetEsxCli

New-AsBuiltReport : You cannot call a method on a null-valued expression.
At line:1 char:1
+ New-AsBuiltReport -Report VMware.vSphere -Target m2-payl-vc01.gci.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

PS C:\windows\system32>
-----------------------------------------------------------------------------------------------------------
**System (please provide the following information about the system from which you are trying to generate a report):**
- OS: Windows 10
- Powershell: 5.1.14393.2879
- PowerCLI 11.2.0
- Manifest   1.0.0      AsBuiltReport
- Script     0.2.0      AsBuiltReport.Cisco.UcsManager      Invoke-AsBuiltReport.Cisco.UcsManager
- Script     1.0.0      AsBuiltReport.Core                  {New-AsBuiltReport, New-AsBuiltConfig, New-AsBuiltReportConfig}
- Script     0.4.1      AsBuiltReport.PureStorage.FlashA... Invoke-AsBuiltReport.PureStorage.FlashArray
- Script     0.4.1      AsBuiltReport.VMware.NSXv           Invoke-AsBuiltReport.VMware.NSXv
- Script     1.0.0      AsBuiltReport.VMware.vSphere        Invoke-AsBuiltReport.VMware.vSphere

![image](https://user-images.githubusercontent.com/50338158/57326256-8e960300-70b8-11e9-91f9-11efca5a3714.png)
![image](https://user-images.githubusercontent.com/50338158/57326639-69ee5b00-70b9-11e9-8224-5c8215850bf9.png)
![image](https://user-images.githubusercontent.com/50338158/57326680-7f638500-70b9-11e9-87a9-474bf46877b4.png)

**Comment by tpcarman** [comment]
Thanks for raising this issue @akvirtualgeek.

Could you please connect to your vCenter Server manually with PowerCLI and run the following

 `get-vmhost | where {$_.Model -notlike "*VMware Mobility Platform*"} | Select Name,Model,ConnectionState`. 

Does the list exclude the HCX dummy host?
Does it exclude any other necessary hosts?

**Comment by akvirtualgeek** [comment]
The command excluded the HCX Dummy Host and listed all of the other hosts without issue. 

![image](https://user-images.githubusercontent.com/50338158/57357614-cd12d880-711f-11e9-82fa-a5339f5f2e0e.png)

**Comment by akvirtualgeek** [comment]
v1.0.1 patch fails on my prod vcenter but completes succssfully on the others. Below is the error that I receive. 

VERBOSE: [ 10:57:45:205 ] [ Document ] - Processing section 'vSphere DRS Configuration' started.
VERBOSE: [ 10:57:45:221 ] [ Document ] - Processing paragraph 'The following table details the vSph[..]'.
VERBOSE: [ 10:57:45:229 ] [ Document ] - Processing blank line.
VERBOSE: [ 10:57:45:257 ] [ Document ] - Processing table 'M2-DSC01-GEN01 vSphere DRS Configuration'.
VERBOSE: [ 10:57:45:449 ] [ Document ] - Processing section 'DRS Cluster Groups' started.
VERBOSE: [ 10:57:45:481 ] [ Document ] - Processing table 'M2-DSC01-GEN01 DRS Cluster Groups'.
New-AsBuiltReport : Cannot bind argument to parameter 'Rows' because it is an empty collection.
At line:1 char:1
+ New-AsBuiltReport -Report VMware.vSphere -Target m2-payl-vc01.gci.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

PS C:\windows\system32>

**Comment by akvirtualgeek** [comment]
![image](https://user-images.githubusercontent.com/50338158/57659124-a58f9600-758d-11e9-87a0-b059f56de92b.png)
![image](https://user-images.githubusercontent.com/50338158/57659151-c2c46480-758d-11e9-99c1-4dca22ed53e3.png)

**Comment by mattallford** [comment]
Hey @akvirtualgeek,

Probably should log a new issue for this, but it looks like it failed on the DRS Cluster Group named "M2-DSC01-GEN01". Can you provide more info about this DRS Group? I suspect it is an object with no members.

@tpcarman, we might need to refine the `if ($DrsClusterGroups)` section to do another if to check for valid membership?

**Comment by akvirtualgeek** [comment]
@mattallford Sorry I've been using this thread to update @tpcarman on the 1.0.1 patch. I'll move my comments over there. In the meantime the HCX fix that Tim provided worked.

Edit line 534 to match this:
            $VMHosts = Get-VMHost -Server $vCenter | where {$_.Model -notlike "*VMware Mobility Platform*"} | Sort-Object Name

**Comment by tpcarman** [comment]
Resolved in #40
