### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by thecavediver** [AsBuiltReport/AsBuiltReport.VMware.vSphere#65]
**Describe the bug**

Every time I run the report I get the same error. I've tried it a bunch of different ways, even on different machines. Its obviously connecting to the vCenter because I see cluster names in the output. I've tried on different vCenters with the same result. I always get this error after "Processing section 'Boot Device' started."

New-AsBuiltReport : Cannot convert value "N/A" to type "System.Int32". Error: "Input string was not in a correct format."
At line:1 char:1
+ New-AsBuiltReport -Target 'vcsa.domain.local' -Username 'adm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**To Reproduce**
Run the script just like provided in the examples. This is a redacted version of the same command I'm using:
New-AsBuiltReport -Target 'vcsa.domain.local' -Username 'administrator@vsphere.local' -Password 'xxxxxxx' -Report VMware.vSphere -Format Html,Word -OutputPath 'C:\Users\MyAccount\Desktop\GeneratedAsBuilts' -Timestamp

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/46495050/62317297-6293df00-b467-11e9-95e9-006ba2467fb8.png)

**System (please provide the following information about the system from which you are trying to generate a report):**
 - OS: Windows 10
 - Windows PowerShell version: Major: 5 Minor: 1 Build: 14393 Revision: 3053
 - 3rd party PowerShell module name and version:
VMware.Vim                    6.7.0.13964812
VMware.VimAutomation.Cis.Core 11.3.0.13964830
VMware.VimAutomation.Common   11.3.0.13964816
VMware.VimAutomation.Core     11.3.0.13964826
VMware.VimAutomation.Sdk      11.3.0.13964823
 - AsBuiltReport Core module version: 1.0.1
 - AsBuiltReport Report module name and version: 1.0.7

**Additional context**
This is failing "out of the box" right after newly installing the modules on a machine. Please help!

**Comment by thecavediver** [comment]
**Update**
When I set the "VMhost" InfoLevel to a value of 2 or lower, I do not hit this error and the script completes execution, successfully generating a file.

**Comment by tpcarman** [comment]
It looks to be related to the `Get-ESXiBootDevice` function. 

Using PowerCLI connect to your vCenter Server and run the following code and let me know if you see the same error.

```powershell
    function Get-ESXiBootDevice {
        <#
    .NOTES
    ===========================================================================
        Created by:    William Lam
        Organization:  VMware
        Blog:          www.virtuallyghetto.com
        Twitter:       @lamw
    ===========================================================================
    .DESCRIPTION
        This function identifies how an ESXi host was booted up along with its boot
        device (if applicable). This supports both local installation to Auto Deploy as
        well as Boot from SAN.
    .PARAMETER VMHostname
        The name of an individual ESXi host managed by vCenter Server
    .EXAMPLE
        Get-ESXiBootDevice
    .EXAMPLE
        Get-ESXiBootDevice -VMHost esxi-01
    #>
        param(
            [Parameter(Mandatory = $false)][PSObject]$VMHost
        )

        $results = @()
        $esxcli = Get-EsxCli -V2 -VMHost $vmhost -Server $vCenter
        $bootDetails = $esxcli.system.boot.device.get.Invoke()

        # Check to see if ESXi booted over the network
        $networkBoot = $false
        if ($bootDetails.BootNIC) {
            $networkBoot = $true
            $bootDevice = $bootDetails.BootNIC
        } elseif ($bootDetails.StatelessBootNIC) {
            $networkBoot = $true
            $bootDevice = $bootDetails.StatelessBootNIC
        }

        # If ESXi booted over network, check to see if deployment
        # is Stateless, Stateless w/Caching or Stateful
        if ($networkBoot) {
            $option = $esxcli.system.settings.advanced.list.CreateArgs()
            $option.option = "/UserVars/ImageCachedSystem"
            try {
                $optionValue = $esxcli.system.settings.advanced.list.Invoke($option)
            } catch {
                $bootType = "Stateless"
            }
            $bootType = $optionValue.StringValue
        }

        # Loop through all storage devices to identify boot device
        $devices = $esxcli.storage.core.device.list.Invoke()
        $foundBootDevice = $false
        foreach ($device in $devices) {
            if ($device.IsBootDevice -eq $true) {
                $foundBootDevice = $true

                if ($device.IsLocal -eq $true -and $networkBoot -and $bootType -ne "Stateful") {
                    $bootType = "Stateless Caching"
                } elseif ($device.IsLocal -eq $true -and $networkBoot -eq $false) {
                    $bootType = "Local"
                } elseif ($device.IsLocal -eq $false -and $networkBoot -eq $false) {
                    $bootType = "Remote"
                }

                $bootDevice = $device.Device
                $bootModel = $device.Model
                $bootVendor = $device.VEndor
                $bootSize = $device.Size
                $bootIsSAS = $device.IsSAS
                $bootIsSSD = $device.IsSSD
                $bootIsUSB = $device.IsUSB
            }
        }

        # Pure Stateless (e.g. No USB or Disk for boot)
        if ($networkBoot -and $foundBootDevice -eq $false) {
            $bootModel = "N/A"
            $bootVendor = "N/A"
            $bootSize = "N/A"
            $bootIsSAS = "N/A"
            $bootIsSSD = "N/A"
            $bootIsUSB = "N/A"
        }

        $tmp = [PSCustomObject]@{
            Host = $vmhost.Name;
            Device = $bootDevice;
            BootType = $bootType;
            Vendor = $bootVendor;
            Model = $bootModel;
            SizeMB = $bootSize;
            IsSAS = $bootIsSAS;
            IsSSD = $bootIsSSD;
            IsUSB = $bootIsUSB;
        }
        $results += $tmp
        $results
    }
```

```powershell
Get-ESXiBootDevice -VMHost <vmhostname>
```

**Comment by thecavediver** [comment]
TIm,

Thanks for the quick response. I've attached a screenshot. It looks to be failing pretty quickly. I _am_ connected to my vCenter. FYI these hosts are auto-deployed.
![image](https://user-images.githubusercontent.com/46495050/62377053-089b2400-b510-11e9-9a42-21a5e82f2d8a.png)

**Comment by mattallford** [comment]
Before running the function, can you enter:

$vCenter = “vcenter.domain.com”

Where vCenter.domain.com is the name of your vCenter server that you used in the connect-VIServer cmdlets? After that retry running the Get-ESXiBootDevice function and let us know the output please!

Cheers, Matt.

**Comment by thecavediver** [comment]
Ok that worked. Most of my hosts are auto-deploy but I have a couple static. I ran against both.
![image](https://user-images.githubusercontent.com/46495050/62378487-ea82f300-b512-11e9-9b13-ec5260a47415.png)

**Comment by mattallford** [comment]
Hey @thecavediver,

Can you run this function against the host in your environment it was running against when the main script errored and share what the behaviour / output is?

It is getting to a particular host and trying to insert a value of "N/A" (string) in to a variable that is set as an integer.

Cheers, Matt.

**Comment by tpcarman** [comment]
@thecavediver any update with this? did you identify the host which was having the issue?
