### ISSUE TITLE
Script terminates at New-AsBuiltReport : A parameter cannot be found that matches parameter name 'Name'.

### ISSUE THREAD

**Issue by Ssitha** [AsBuiltReport/AsBuiltReport.VMware.vSphere#66]
I have just freshly installed the required modules for this today, & here is the entry that gets this error.

New-AsBuiltReport -Target 'vcenterserver.tesi.local' -Credential $Creds -Report VMware.vSphere -Format Html,Text  -OutputPath 'C:\Reports\' -EnableHealthCheck 

then gives me

New-AsBuiltReport : A parameter cannot be found that matches parameter name 'Name'.
At line:1 char:1
+ New-AsBuiltReport -Target 'vcenterserver.tesi.local' -Credential $Cre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Comment by mattallford** [comment]
Hi @Ssitha,

Apologies on no response, it looks like both Tim and I overlooked getting back to you on this.

Have you happened to have any luck with it yet?

If not, can you confirm versions of PowerCLI, Powershell, Windows, VMware environment, etc? Can you rerun with -Verbose and see if any additional output is provided and post a screenshot?

Cheers, Matt.

**Comment by tpcarman** [comment]
Stale issue. No response.
