### ISSUE TITLE
Get-DRSClusterGroup CMDLet

### ISSUE THREAD

**Issue by googleface** [AsBuiltReport/AsBuiltReport.VMware.vSphere#67]
Hi Chaps,

I have followed the installation instructions but appear to missing a CMDLet

![image](https://user-images.githubusercontent.com/23346932/63943715-1a68dc00-ca68-11e9-97c3-e2f736e58089.png)

Windows 2016 Std
Powershell Version: 5.1.14393.3053
VMware PowerCLI Version: 6.5 Release 1 build 4624819

![image](https://user-images.githubusercontent.com/23346932/63944091-d5917500-ca68-11e9-8d87-4baa6ec65156.png)

Hope you can help.

Cheers
Scott

**Comment by mattallford** [comment]
Hey Scott,

Thanks for checking out the project and letting us know of your issue.

Get-DrsClusterGroup is a PowerCLI cmdlet that looks like was introduced in 6.5.1 (https://blogs.vmware.com/PowerCLI/2017/06/spotlight-new-drs-cmdlets.html). Is there any chance you can upgrade PowerCLI? We're doing most of our testing on newer versions of the PowerCLI module these days (11.x).

Let us know how you get on.

Cheers, Matt.

**Comment by googleface** [comment]
Hey Matt,

Thanks for the quick response.

Hold fast I'm a thick Yorkshireman, I'll update the module and come back to you, keen to get this working it looks awesome. :-)

**Comment by mattallford** [comment]
Haha, no worries Scott! I happened to be awake doing some study, so seeing this come in was a good oppotunity for procrastination :)

Do let us know how you get on with it, or if you run in to any other issues let us know and we'll help out.

Cheers, Matt.

**Comment by googleface** [comment]
LOL, nowt wrong with a bout of procrastination, helps you get through the day.

Getting this error now.

![image](https://user-images.githubusercontent.com/23346932/63952470-90287400-ca77-11e9-9b65-06433bb6ca55.png)

Any ideas please?

Cheers
Scott

**Comment by mattallford** [comment]
What version of vSphere and what version of ESXi is that host that Get-EsxCli is failing on?

I've not come across that before, @tpcarman ?

**Comment by tpcarman** [comment]
I've never seen that before either. Do you have anything out of the ordinary deployed in your environment, witness host or something?

**Comment by googleface** [comment]
Hi Guys,

vSphere Version: 5.5.0 Build 4180647
ESXi: VMware ESX, 4.1.0, 582267 - (Therein lies the problem?)

Thx
Scott

**Comment by tpcarman** [comment]
Ha! Yeah not going to happen :)

**Comment by googleface** [comment]
Is there anyway to bypass non supported hosts?

**Comment by tpcarman** [comment]
Yeah I’m sure it is possible but I have to draw the line somewhere. ESX 4.1 went out of support many years ago. I just really don’t want to be coding around every unique use case.

**Comment by mattallford** [comment]
We don't have that functionality built in, but it's something we can put in as a feature request.

I don't think it would be too hard to code around it, @tpcarman is it just a matter of a filter on Get-VMHost in the vsphere As Built Report?

**Comment by googleface** [comment]
Fully understand Tim, just wondered if there was any | Select-Object or Where-Object could have filtered these out during the CMDLet execution, I have 4 x 5.0.0 hosts & 1 x 4.1 host on this VC.

I guess I'm unable to use against this VC then?

Appreciate the help., Scott

**Comment by googleface** [comment]
I'll give it a bash against my 6.5 VC now and see how that goes.

**Comment by googleface** [comment]
Thing of beauty this lads, haven't felt this good since Michael Owen score against Argentina in the 1998 World Cup. Worked a treat on VC 6.5, did throw this warning up, not sure if this means certain VUM info wasn't extracted or not?

![image](https://user-images.githubusercontent.com/23346932/64014480-1bf2dc80-cb1a-11e9-8bcf-b93aabb2367f.png)

Thanks again, this module is unreal.... package it and sell it :-)

**Comment by mattallford** [comment]
Thanks for the feedback Scott :)

That warning is OK to ignore for the purposes of data collection, the VUM information will still have been extracted. The VUM cmdlets in PowerCLI don't use the connection to the vCenter Server, it establishes another connection, so unless the VUM service has a trusted cert, you'll get this warning as well.

**Comment by googleface** [comment]
Brilliant, thanks again chaps, wait till I show my superiors this :-)

**Comment by googleface** [comment]
Chaps, can this script map DataStores back to NetApp devices?

**Comment by mattallford** [comment]
Hey Scott,

Sorry, I didn't see this last message.

With the current functionality, no, as the script is just looking at the context of the vSphere environment and not at the underlying storage platform as well.

**Comment by tpcarman** [comment]
@googleface I will include this in the next update, however if you wanted to test on your environment, modify the following line in `Invoke-AsBuiltReport.VMware.vSphere.ps1`

This will exclude ESX/ESXi hosts prior to vSphere 5.0

**From this**
`$VMHosts = Get-VMHost -Server $vCenter | Where-Object { $_.Model -notlike "*VMware Mobility Platform"} | Sort-Object Name` 

**To this**
`$VMHosts = Get-VMHost -Server $vCenter | Where-Object { $_.Model -notlike "*VMware Mobility Platform" -and $_.Version -gt 5} | Sort-Object Name`

Please let me know if this resolves your issue.
