### ISSUE TITLE
Error when trying to use XML Output Reports

### ISSUE THREAD

**Issue by JrDaily** [AsBuiltReport/AsBuiltReport.VMware.vSphere#71]
**Describe the bug**
XML Report Output allows XML tag names to start with a Number which is not allowed by [standards](https://www.w3.org/TR/xml/#NT-NameStartChar) and causes errors when trying to use or view it.

**To Reproduce**
1. Create a VMware report using something like:
_New-AsBuiltReport -Target 'vcenter-01.corp.local','vcenter-02.corp.local' -Username 'An_Administrator' -Password 'Password' -Report VMware.vSphere -Format Html,XML -OutputPath 'C:\Users\Tim\Documents' -EnableHealthCheck_

2. When finished, open the XML report in another XML viewer or editor such as XML Editor, Excel, Visual Studio, etc...

3. It will either fail to load or show errors when loaded. See screenshots below

**Expected behavior**
A usable XML file that can be imported or manipulated in other tools without errors. 

**Screenshots**
![image](https://user-images.githubusercontent.com/57505093/68425745-53aa8000-016c-11ea-9937-48f39cd2fe8a.png)

![image](https://user-images.githubusercontent.com/57505093/68426022-de8b7a80-016c-11ea-8838-aead8dc426b6.png)

**System:**
 - OS: Windows
 - Windows PowerShell version: 5.1
 - 3rd party PowerShell module name and version: VMware PowerCLI 11.4
 - AsBuiltReport Core module version: 1.0.3
 - AsBuiltReport Report module name and version: AsBuiltReport.VMware.vSphere 1.0.7

**Suggestions:**

A quick web search found a couple of ways to "fix" this:

1. Prepend all of the XML "names" with something like an _ to make it valid - ex. <_8112c111-d06a-42e7-8bbd-0e70670a153b name="vcsa.qa.dmz">

2. Haven't dug into your code to see if it is being used as anything other than a simple random tracker for the XML, but change it to use something else to create the random tag name or adjust the code so that it doesn't allow the random tag name to begin with number

3. If still want to use the number, you can just encode the first char to use the hex equivalent no matter if it is alpha or numeric (ex _x0038_ to represent 8) as seen in this [stackoverflow thread](https://stackoverflow.com/questions/2087108/encoding-xml-element-name-beginning-with-a-number). This would make it harder to "look" at and since it is non-standard, it might cause additional issues or weirdness when other XML tools might not handle it properly as seen in this [thread](https://stackoverflow.com/questions/19677315/xml-tagname-starting-with-number-is-not-working).

Obviously I think that option 1 would be the easiest and quickest fix, but since I haven't looked into the code, I don't know if it would cause other issues.

**Comment by tpcarman** [comment]
I have successfully tested opening and XML file in Visual Studio Code, Internet Explorer and MS Excel, with the latest version of PScribo (0.7.26) and the VMware vSphere As Built Report (1.1.3). I do not experience the issue you describe. Could you please test on these newer releases and reopen this issue if this problem still exists.
