### ISSUE TITLE
Problem with start or create the Reportconfig

### ISSUE THREAD

**Issue by TR-HD** [AsBuiltReport/AsBuiltReport.VMware.vSphere#72]
**Describe the bug**

Running the command
New-AsBuiltReport -Report VMware.vSphere -Target vCenterFQDN -Credential (Get-Credential) -Format HTML,Word -OutputPath 'C:\Master\VMware\AsBuiltReport\Reports' -TimeStamp -EnableHealthcheck

**Expected behavior**
Not running in a Error or smooth go trough

**Screenshots**
![image](https://user-images.githubusercontent.com/58432523/69968458-bea46800-151a-11ea-9694-9ed235a17833.png)

**System (please provide the following information about the system from which you are trying to generate a report):**
 - OS: [e.g. Windows 10]
Windows 10 Enterprise
 - Windows PowerShell version [Provide output from the following command: `$PSVersionTable.PSVersion`]
Major  Minor  Build  Revision
5      1      16299  1146
 - 3rd party PowerShell module name and version [e.g. VMware PowerCLI 11.2]
VMware PowerCLI 6.5.0R1
 - AsBuiltReport Core module version [e.g. 1.0.0]
1.0.2
 - AsBuiltReport Report module name and version [e.g. AsBuiltReport.VMware.vSphere 1.0.0]
1.0.7

**Additional context**

**Comment by mattallford** [comment]
Hi @TR-HD 

Thanks for logging the issue. Can you please pate the error message in here so I can translate to English, or provide a version that is in English?

From what I can tell, it can't find the cmdlet Get-PatchBaseline on your system. This should be a part of the VMware.VumAutomation Powershell module, do you have this installed?

I noticed you are running PowerCLI 6.5.0R1 which is several years old. Are you able to upgrade to a newer release in the 11.x stream and retry running the as built report?

Cheers, Matt.
