### ISSUE TITLE
New-AsBuiltReport : Cannot convert value "N/A" to type "System.Int32". Error: "Input string was not in a correct

### ISSUE THREAD

**Issue by vtrimi** [AsBuiltReport/AsBuiltReport.VMware.vSphere#76]
**Describe the bug**
VERBOSE: [ 19:59:33:522 ] [ Document ] - Processing section 'Hardware' started.
VERBOSE: [ 19:59:33:538 ] [ Document ] - Processing paragraph 'The following section details the ho[..]'.
VERBOSE: [ 19:59:33:538 ] [ Document ] - Processing blank line.
VERBOSE: [ 19:59:34:572 ] [ Document ] - Processing table 'xxxx ESXi Host Detailed
Information'.
VERBOSE: [ 19:59:34:603 ] [ Document ] - Processing section 'Boot Device' started.
New-AsBuiltReport : Cannot convert value "N/A" to type "System.Int32". Error: "Input string was not in a correct
format."
At line:1 char:1
+ New-AsBuiltReport -Report VMware.vSphere -Target xxxx -User ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

-------------------------------------
The latest version 1.1.3. (AsBuiltReport) and latest PowerCLI version.
Boot Device from the server "None" --> Stateless Auto Deploay

**Comment by orb71** [comment]
Hi Trim,

Do you mind posting the following output from your console please ?

esxcli system boot device get
esxcli system settings advanced list 
esxcli system settings advanced list -o /UserVars/ImageCachedSystem
esxcli storage core device list

Regards,
Oli

**Comment by vtrimi** [comment]
Hi Oli,

Thank you for coming back to me.

Unfortunately i cant send you the core device list (more then 100LUNs). 
It would be amazing just to skip if something fails like the issue i had or similar and not stop the hole script.

root@xxxx:~] esxcli system boot device get
Boot Filesystem UUID:
Boot NIC: xx-xx-xx-xx-xx-xx-xx
Stateless Boot NIC:

[root@xxxx:~] esxcli system settings advanced list -o /UserVars/ImageCachedSystem
Unable to find option ImageCachedSystem

BR ./trim

**Comment by orb71** [comment]
Ouch 100!

I wasn't looking the right direction anyway. If you need a quick fix go edit Invoke-AsBuiltReport.VMware.vSphere.ps1 in your module directory

Line 372 : $bootSize = "N/A" and replace it by $bootSize = 0 for dirty fix

The problem is at line 1868, it is missing a check.

'Size' = Switch ($ESXiBootDevice.SizeMB){
       'N/A' { 'N/A' }
       default{"$([math]::Round($ESXiBootDevice.SizeMB / 1024, 2)) GB"}
}

Oli

**Comment by vtrimi** [comment]
hi Oli,

Yes, sir. this solved my issue!
Thank you very much. I hope this helps as well other people who use Auto Deploy.

BR ./trim

**Comment by tpcarman** [comment]
Awesome work @orb71. Thank you. I've found a few other issues which I have pushed to the `dev` branch. Expect this fix there shortly too.

**Comment by orb71** [comment]
@tpcarman ,  glad to help and  I don't mind submiting pull request. Do you want me to submit a bug report for the Get-PCIDeviceDetail function as well?
