### ISSUE TITLE
Cannot bind argument to parameter 'Rows' because it is an empty collection.

### ISSUE THREAD

**Issue by EloiseJory** [AsBuiltReport/AsBuiltReport.VMware.vSphere#79]
Report works fine on one 6.5 vcenter, but not the 6.5 or other 6.7's
**To Reproduce**
New-AsBuiltReport -Report VMware.vSphere -Target 123.456.789  -Username vcheck -Password password -Format HTML,Word -OutputPath 'd:\Reports\'

**Expected behavior**
Report should run with no errors.

**Screenshots**
VERBOSE: [ 14:13:43:903 ] [ Document ] - Processing section 'Historical Statistics' completed.
VERBOSE: [ 14:13:43:903 ] [ Document ] - Processing section 'Licensing' started.
VERBOSE: [ 14:13:43:950 ] [ Document ] - Processing table 'Licensing'.
New-AsBuiltReport : Cannot bind argument to parameter 'Rows' because it is an empty collection.
At line:1 char:1
+ New-AsBuiltReport -Report VMware.vSphere -Target 123.456.789 -Usern ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**System (please provide the following information about the system from which you are trying to generate a report):**
 - OS: server 2016
 - Windows PowerShell version [Provide output from the following command: PS H:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  2969

 - 3rd party PowerShell module name and version -VMware.VimAutomation.Core 10.0.0.7893909
 - AsBuiltReport Core module version   1.0.3
 - AsBuiltReport Report module name and version AsBuiltReport.VMware.vSphere 1.0.7

**Additional context**
Had this issue on previous builds, thought Id try again on latest build but seem to have hit the same licence row isssue

**Comment by tpcarman** [comment]
@EloiseJory The latest release for the VMware vSphere report is 1.1.3. Could you please update and report back. 

`Update-Module AsBuiltReport.VMware.vSphere`

**Comment by EloiseJory** [comment]
> @EloiseJory The latest release for the VMware vSphere report is 1.1.3. Could you please update and report back.
> 
> `Update-Module AsBuiltReport.VMware.vSphere`

hmm thought  I had the latest build - whats the link ?

**Comment by mattallford** [comment]
@EloiseJory  the Powershell code Tim posted above should upgrade you to the latest build from the PowerShell gallery.

**Comment by EloiseJory** [comment]
I need a manual download sorry - security doensn't allow pshell to access the net. Probably why I'm struggling with version control...

**Comment by tpcarman** [comment]
If you need some assistance with how to install the modules offline, be sure to check the instructions [here](https://www.asbuiltreport.com/documentation/installation/).

**Comment by EloiseJory** [comment]
I can install them ok, just need an up to date download source.    Was downloading nupkg files from powershell gallery

**Comment by tpcarman** [comment]
I will close this issue. Please reopen if the problem still persists after updating to the latest release.

**Comment by EloiseJory** [comment]
updated to 1.1.3  and get the same error



----------------------------------------------
 <       As Built Report Configuration      >
----------------------------------------------
Would you like to save the As Built configuration file? (y/n): n
New-AsBuiltReport : Cannot bind argument to parameter 'Rows' because it is an empty collection.
At line:1 char:1
+ New-AsBuiltReport -Report VMware.vSphere -Target zzz.zz.zzxx -Usern ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

PS H:\> get-module AsBuiltReport.VMware.vSphere

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.3      AsBuiltReport.VMware.vSphere        Invoke-AsBuiltReport.VMware.vSphere


PS H:\>
